### ISSUE TITLE
Html comment breaks validation

### ISSUE THREAD

**Issue by loopdream** [mdb/middleman-build-reporter#6]
The fingerprint comment ends in `--!>` but it should be `-->`
This isn't correct html and fails validation. 
Plus this causes middleman's minify html it strips everything out of the <head> tag

**Comment by mdb** [comment]
Thank you! Apologies for overlooking this. I've released a fix in version `0.0.4`, which is now available on Rubygems.org.

Please let me know if you have further problems.
